FROM ghcr.io/navikt/mock-oauth2-server:2.1.0
# ./gradlew -Djib.from.platforms=linux/amd64 jibDockerBuild #
# copies the configuration from the YAML file,

EXPOSE 8282
# No need for entrypoints, as this will only be to get some tokens yeah